import React from "react";

const Country = () => {
  return (
    <>
      <option value="UM">ABD Minör Outlying Adaları</option>
      <option value="VI">ABD Virgin Adaları</option>
      <option value="AF">Afganistan</option>
      <option value="AX">Aland Adaları</option>
      <option value="DE">Almanya</option>
      <option value="AS">Amerikan Samoası</option>
      <option value="AD">Andora</option>
      <option value="AO">Angola</option>
      <option value="AI">Anguilla</option>
      <option value="AQ">Antarktika</option>
      <option value="AG">Antigua ve Barbuda</option>
      <option value="AR">Arjantin</option>
      <option value="AL">Arnavutluk</option>
      <option value="AW">Aruba</option>
      <option value="AU">Avustralya</option>
      <option value="AT">Avusturya</option>
      <option value="AZ">Azerbaycan</option>
      <option value="BL">BL</option>
      <option value="BQ">BQ</option>
      <option value="BS">Bahamalar</option>
      <option value="BH">Bahreyn</option>
      <option value="BD">Bangladeş</option>
      <option value="BB">Barbados</option>
      <option value="EH">Batı Sahra</option>
      <option value="BY">Belarus</option>
      <option value="BZ">Belize</option>
      <option value="BE">Belçika</option>
      <option value="BJ">Benin</option>
      <option value="BM">Bermuda</option>
      <option value="BT">Bhutan</option>
      <option value="AE">Birleşik Arap Emirlikleri</option>
      <option value="US">Birleşik Devletler</option>
      <option value="GB">Birleşik Krallık</option>
      <option value="VG">Birleşik Krallık Virgin Adaları</option>
      <option value="BO">Bolivya</option>
      <option value="BA">Bosna-Hersek</option>
      <option value="BW">Botsvana</option>
      <option value="BV">Bouvet Adası</option>
      <option value="BR">Brezilya</option>
      <option value="BN">Bruney Sultanlığı</option>
      <option value="BG">Bulgaristan</option>
      <option value="BF">Burkina Faso</option>
      <option value="BI">Burundi</option>
      <option value="CU">CU</option>
      <option value="CW">CW</option>
      <option value="KY">Cayman Adaları</option>
      <option value="GI">Cebelitarık</option>
      <option value="DZ">Cezayir</option>
      <option value="CX">Christmas Adası</option>
      <option value="DJ">Cibuti</option>
      <option value="CC">Cocos Adaları</option>
      <option value="CK">Cook Adaları</option>
      <option value="DK">Danimarka</option>
      <option value="CD">Demokratik Kongo Cumhuriyeti</option>
      <option value="DM">Dominik</option>
      <option value="DO">Dominik Cumhuriyeti</option>
      <option value="TL">Doğu Timor</option>
      <option value="EC">Ekvador</option>
      <option value="GQ">Ekvator Ginesi</option>
      <option value="SV">El Salvador</option>
      <option value="ID">Endonezya</option>
      <option value="ER">Eritre</option>
      <option value="AM">Ermenistan</option>
      <option value="EE">Estonya</option>
      <option value="SZ">Esvatini</option>
      <option value="ET">Etiyopya</option>
      <option value="FK">Falkland Adaları</option>
      <option value="FO">Faroe Adaları</option>
      <option value="MA">Fas</option>
      <option value="FJ">Fiji</option>
      <option value="CI">Fildişi Sahili</option>
      <option value="PH">Filipinler</option>
      <option value="PS">Filistin İşgal Bölgesi</option>
      <option value="FI">Finlandiya</option>
      <option value="FR">Fransa</option>
      <option value="GF">Fransız Guyanası</option>
      <option value="PF">Fransız Polinezyası</option>
      <option value="GA">Gabon</option>
      <option value="GM">Gambiya</option>
      <option value="GH">Gana</option>
      <option value="GN">Gine</option>
      <option value="GW">Gine-Bissau</option>
      <option value="GD">Grenada</option>
      <option value="GL">Grönland</option>
      <option value="GP">Guadeloupe</option>
      <option value="GU">Guam</option>
      <option value="GT">Guatemala</option>
      <option value="GG">Guernsey</option>
      <option value="GY">Guyana</option>
      <option value="ZA">Güney Afrika</option>
      <option value="GS">Güney Georgia ve Güney Sandwich Adaları</option>
      <option value="KR">Güney Kore Cumhuriyeti</option>
      <option value="TF">Güneydeki Fransız Bölgeleri</option>
      <option value="GE">Gürcistan</option>
      <option value="HT">Haiti</option>
      <option value="HM">Heard ve Mc Donald Adaları</option>
      <option value="IN">Hindistan</option>
      <option value="IO">Hint Okyanusundaki İngiliz Bölgesi</option>
      <option value="NL">Hollanda</option>
      <option value="HN">Honduras</option>
      <option value="HK">Hong Kong</option>
      <option value="HR">Hırvatistan</option>
      <option value="IQ">Irak</option>
      <option value="JM">Jamaika</option>
      <option value="JP">Japonya</option>
      <option value="JE">Jersey</option>
      <option value="KH">Kamboçya</option>
      <option value="CM">Kamerun</option>
      <option value="CA">Kanada</option>
      <option value="ME">Karadağ</option>
      <option value="QA">Katar</option>
      <option value="KZ">Kazakistan</option>
      <option value="KE">Kenya</option>
      <option value="KI">Kiribati</option>
      <option value="CO">Kolombiya</option>
      <option value="KM">Komorlar</option>
      <option value="CG">Kongo</option>
      <option value="XK">Kosova</option>
      <option value="CR">Kostarika</option>
      <option value="KW">Kuveyt</option>
      <option value="MP">Kuzey Mariana Adaları</option>
      <option value="CY">Kıbrıs</option>
      <option value="KG">Kırgızistan</option>
      <option value="LA">Lao Demokratik Halk Cumhuriyeti</option>
      <option value="LS">Lesotho</option>
      <option value="LV">Letonya</option>
      <option value="LR">Liberya</option>
      <option value="LY">Libya</option>
      <option value="LI">Liechtenstein</option>
      <option value="LT">Litvanya</option>
      <option value="LB">Lübnan</option>
      <option value="LU">Lüksemburg</option>
      <option value="MF">MF</option>
      <option value="HU">Macaristan</option>
      <option value="MG">Madagaskar</option>
      <option value="MO">Makao</option>
      <option value="MK">Makedonya Cumhuriyeti</option>
      <option value="MW">Malavi</option>
      <option value="MV">Maldivler</option>
      <option value="MY">Malezya</option>
      <option value="ML">Mali</option>
      <option value="MT">Malta</option>
      <option value="IM">Man Adası</option>
      <option value="MH">Marshall Adaları</option>
      <option value="MQ">Martinik</option>
      <option value="MU">Mauritius</option>
      <option value="YT">Mayotte</option>
      <option value="MX">Meksika</option>
      <option value="FM">Mikronezya Federal Devletleri</option>
      <option value="MD">Moldova Cumhuriyeti</option>
      <option value="MC">Monako</option>
      <option value="MS">Montserrat</option>
      <option value="MR">Moritanya</option>
      <option value="MZ">Mozambik</option>
      <option value="MN">Moğolistan</option>
      <option value="MM">Myanmar</option>
      <option value="EG">Mısır</option>
      <option value="NA">Namibya</option>
      <option value="NR">Nauru</option>
      <option value="NP">Nepal</option>
      <option value="NE">Nijer</option>
      <option value="NG">Nijerya</option>
      <option value="NI">Nikaragua</option>
      <option value="NU">Niue</option>
      <option value="NF">Norfolk Adası</option>
      <option value="NO">Norveç</option>
      <option value="CF">Orta Afrika Cumhuriyeti</option>
      <option value="PK">Pakistan</option>
      <option value="PW">Palau</option>
      <option value="PA">Panama</option>
      <option value="PG">Papua Yeni Gine</option>
      <option value="PY">Paraguay</option>
      <option value="PE">Peru</option>
      <option value="PN">Pitcairn Adaları</option>
      <option value="PL">Polonya</option>
      <option value="PT">Portekiz</option>
      <option value="PR">Porto Riko</option>
      <option value="RE">Reunion</option>
      <option value="RO">Romanya</option>
      <option value="RW">Ruanda</option>
      <option value="RU">Rusya Federasyonu</option>
      <option value="SS">SS</option>
      <option value="SX">SX</option>
      <option value="SH">Saint Helena</option>
      <option value="KN">Saint Kitts ve Nevis</option>
      <option value="LC">Saint Lucia</option>
      <option value="PM">Saint Pierre ve Miquelon</option>
      <option value="VC">Saint Vincent ve Grenadinler</option>
      <option value="WS">Samoa</option>
      <option value="SM">San Marino</option>
      <option value="ST">Sao Tome ve Principe</option>
      <option value="SN">Senegal</option>
      <option value="SC">Seyşeller</option>
      <option value="SL">Sierra Leone</option>
      <option value="SG">Singapur</option>
      <option value="SK">Slovakya</option>
      <option value="SI">Slovenya</option>
      <option value="SB">Solomon Adaları</option>
      <option value="SO">Somali</option>
      <option value="LK">Sri Lanka</option>
      <option value="SD">Sudan</option>
      <option value="SR">Surinam</option>
      <option value="SY">Suriye</option>
      <option value="SA">Suudi Arabistan</option>
      <option value="SJ">Svalbard ve Jan Mayen</option>
      <option value="RS">Sırbistan</option>
      <option value="TJ">Tacikistan</option>
      <option value="TZ">Tanzanya</option>
      <option value="TH">Tayland</option>
      <option value="TW">Tayvan</option>
      <option value="TG">Togo</option>
      <option value="TK">Tokelau</option>
      <option value="TO">Tonga</option>
      <option value="TT">Trinidad ve Tobago</option>
      <option value="TN">Tunus</option>
      <option value="TV">Tuvalu</option>
      <option value="TR">
        Türkiye
      </option>
      <option value="TM">Türkmenistan</option>
      <option value="TC">Türk ve Caicos Adaları</option>
      <option value="UG">Uganda</option>
      <option value="UA">Ukrayna</option>
      <option value="OM">Umman</option>
      <option value="UY">Uruguay</option>
      <option value="VU">Vanuatu</option>
      <option value="VA">Vatikan</option>
      <option value="VE">Venezuela</option>
      <option value="VN">Vietnam</option>
      <option value="WF">Wallis ve Futuna Adaları</option>
      <option value="YE">Yemen</option>
      <option value="NC">Yeni Kaledonya</option>
      <option value="NZ">Yeni Zelanda</option>
      <option value="CV">Yeşilburun</option>
      <option value="GR">Yunanistan</option>
      <option value="ZM">Zambiya</option>
      <option value="ZW">Zimbabve</option>
      <option value="TD">Çad</option>
      <option value="CZ">Çek Cumhuriyeti</option>
      <option value="CN">Çin</option>
      <option value="UZ">Özbekistan</option>
      <option value="JO">Ürdün</option>
      <option value="IR">İran</option>
      <option value="IE">İrlanda</option>
      <option value="ES">İspanya</option>
      <option value="IL">İsrail</option>
      <option value="SE">İsveç</option>
      <option value="CH">İsviçre</option>
      <option value="IT">İtalya</option>
      <option value="IS">İzlanda</option>
      <option value="CL">Şili</option>
    </>
  );
};

export default Country;
